AllCops:
  TargetRubyVersion: 3.3.4
  Exclude:
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

